--- 
 - name: Automatisation de la Création utilisateur
   hosts: node
   remote_user: "{{ utilisateur }}"
   become: yes
   become_method: sudo
   vars:
     user : "{{ new_user }}"

   roles: 
     - Update
     - creation
...
